// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VivazAPI.Data;

namespace VivazAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210412194609_CreateActiveTypes")]
    partial class CreateActiveTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("VivazAPI.Models.ActiveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WarrantyInYears")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ActiveTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("659fa627-61c1-4bc6-8be6-aea553bdc0f2"),
                            Description = "Instalação de equipamentos industrializados, como aquecedores, motobombas, filtros e interfones.",
                            WarrantyInYears = 1
                        },
                        new
                        {
                            Id = new Guid("7ffaa512-8988-4e61-9192-9f32ee500e4e"),
                            Description = "Borrachas, escovas, articulações, fechos e roldanas de esquadrias de alumínio ou PVC.",
                            WarrantyInYears = 2
                        },
                        new
                        {
                            Id = new Guid("8ac35cfa-7237-4d55-8aa5-5c4a6e5a7d29"),
                            Description = "Fundações, estruturas principais e periféricas, contenções e arrimos, envolvendo segurança e estabilidade.",
                            WarrantyInYears = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
